[package]
name = "mini-blockchain"
version = "0.1.0"
edition = "2021"

[dependencies]

secp256k1 = { version = "0.30.0", features = ["rand"] }
sha2 = "0.10.8"
serde = { version = "1.0", features = ["derive"] }
hex-literal = "0.4.1"
hex = "0.4"
chrono = "0.4"